// Generated by CoffeeScript 1.6.2
(function() {
  define('EaseLib', function() {
    var Easings;

    Easings = (function() {
      function Easings(o) {
        this.createEasings();
      }

      Easings.prototype.createEasings = function() {
        var QuakeIn, QuakeOut;

        this.Quake = {};
        this.Quake.Out = QuakeOut = (function() {
          function QuakeOut(coef) {
            if (coef == null) {
              coef = 5;
            }
            return function(t) {
              var b;

              b = Math.exp(-t * coef) * Math.cos(Math.PI * 2 * t * coef);
              return 1 - b;
            };
          }

          return QuakeOut;

        })();
        return this.Quake.In = QuakeIn = (function() {
          function QuakeIn(coef) {
            if (coef == null) {
              coef = 5;
            }
            return function(t) {
              var b;

              b = t * t * Math.cos(Math.PI * 2 * t * coef);
              return b;
            };
          }

          return QuakeIn;

        })();
      };

      return Easings;

    })();
    return new Easings;
  });

}).call(this);
