// Generated by CoffeeScript 1.6.2
require(['createGraph', 'Tween', 'EaseLib'], function(createGraph, TWEEN, EaseLib) {
  var animate, init;

  init = function() {
    var target;

    target = document.getElementById("target");
    target.appendChild(document.createElement("br"));
    target.appendChild(createGraph("Quake.Out", new EaseLib.Quake.Out));
    target.appendChild(createGraph("Quake.In", new EaseLib.Quake.In));
    target.appendChild(createGraph("Quake.InOut", new EaseLib.Quake.InOut));
    target.appendChild(document.createElement("br"));
    target.appendChild(createGraph("Quartic.In", TWEEN.Easing.Quartic.In));
    target.appendChild(createGraph("Quartic.Out", TWEEN.Easing.Quartic.Out));
    return target.appendChild(createGraph("Quartic.InOut", TWEEN.Easing.Quartic.InOut));
  };
  animate = function() {
    requestAnimationFrame(animate);
    return TWEEN.update();
  };
  init();
  return animate();
});
